CLIENT_PATH := client
CLIENT_SRC_PATH := $(CLIENT_PATH)/src
CLIENT_EXECUTABLE := client

SERVER_PATH := server
SERVER_SRC_PATH := $(SERVER_PATH)/src
SERVER_EXECUTABLE := server

BIN := bin


all: $(BIN)/$(CLIENT_EXECUTABLE) $(BIN)/$(SERVER_EXECUTABLE)

$(BIN)/$(CLIENT_EXECUTABLE): $(CLIENT_SRC_PATH)/*.cpp
	$(MAKE) -C $(CLIENT_PATH) all

$(BIN)/$(SERVER_EXECUTABLE): $(SERVER_SRC_PATH)/*.cpp
	$(MAKE) -C $(SERVER_EXECUTABLE) all

run-client: $(BIN)/$(CLIENT_EXECUTABLE)
	$(BIN)/$(CLIENT_EXECUTABLE)

run-server: $(BIN)/$(SERVER_EXECUTABLE)
	$(BIN)/$(SERVER_EXECUTABLE)
