#include <string>

#define ERROR_MISSING_ARGS 1
#define ERROR_CONFIGURATION_FAILED 2
#define ERROR_OPEN_SOCKET 3
#define ERROR_CONNECTION_SOCKET_FAILED 4
#define ERROR_SENDING_MESSAGE 5
#define ERROR_RECEIVING_MESSAGE 6
